const valor = 10;

try {

    valor = 2
} catch (err) {
    console.log(`Erro ${err}`)
}